
services:

  app: 
    build:                                             
      dockerfile: Dockerfile.app                  
    

  web:
    build:                                              
      dockerfile: Dockerfile.web
    ports:
      - "80:80"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

    depends_on:
      - app

     


