apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-upp
spec:
  selector:
    matchLabels:
      app: app-upp
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: app-upp
    spec:
      containers:
      - name: app-upp
        image: visha1308/test-repo-app:latest
        
