apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-upp
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: app-upp
  template:
    metadata:
      labels:
        app: app-upp
    spec:
      containers:
      - name: app-upp
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - containerPort: 80
